apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  selector:
    app: influxdb
  ports:
  - port: 8086
    targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-dep
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb-pod
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb-img
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /var/lib/influxdb
            name: influxdb-vol
          - mountPath: /var/run/docker.sock
            name: docker-sock
        ports:
        - containerPort: 8086
      volumes:
        - name: influxdb-vol
          persistentVolumeClaim:
            claimName: influxdb-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock