apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-dep
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 21